#!/bin/bash
# Setup script for Healing Space application

set -e

echo "🌿 Healing Space - Setup Script"
echo "================================"
echo ""

# Check Python version
echo "Checking Python version..."
python3 --version || { echo "❌ Python 3 is required"; exit 1; }
echo "✅ Python 3 found"
echo ""

# Create virtual environment (optional)
read -p "Create virtual environment? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Creating virtual environment..."
    python3 -m venv venv
    source venv/bin/activate || . venv/Scripts/activate
    echo "✅ Virtual environment created and activated"
fi
echo ""

# Install dependencies
echo "Installing dependencies..."
pip install -r requirements.txt
echo "✅ Dependencies installed"
echo ""

# Generate keys
echo "Generating encryption keys..."
ENCRYPTION_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
PIN_SALT=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
echo "✅ Keys generated"
echo ""

# Create .env file if it doesn't exist
if [ ! -f .env ]; then
    echo "Creating .env file..."
    cat > .env << EOF
# Generated by setup.sh on $(date)

# Runtime mode
DEBUG=1

# Security keys (automatically generated)
ENCRYPTION_KEY=$ENCRYPTION_KEY
PIN_SALT=$PIN_SALT

# Required: Add your Groq API key here
GROQ_API_KEY=your_groq_api_key_here

# API endpoint
API_URL=https://api.groq.com/openai/v1/chat/completions

# Optional: HashiCorp Vault
# VAULT_ADDR=https://vault.example.com
# VAULT_TOKEN=your_vault_token_here

# Optional: SFTP Export
# SFTP_HOST=sftp.example.com
# SFTP_PORT=22
# SFTP_USER=username
# SFTP_PASS=password

# Optional: Webhook Alerts
# ALERT_WEBHOOK_URL=https://hooks.slack.com/services/YOUR/WEBHOOK/URL
EOF
    echo "✅ .env file created"
    echo ""
    echo "⚠️  IMPORTANT: Edit .env and add your GROQ_API_KEY"
else
    echo "ℹ️  .env file already exists, skipping creation"
fi
echo ""

# Create necessary directories
echo "Creating directories..."
mkdir -p backups
mkdir -p audit_logs
echo "✅ Directories created"
echo ""

# Run tests
read -p "Run tests to verify setup? (Y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    echo "Running tests..."
    export DEBUG=1
    export PIN_SALT="$PIN_SALT"
    export ENCRYPTION_KEY="$ENCRYPTION_KEY"
    pytest -v tests/ || echo "⚠️  Some tests failed, but you can still proceed"
fi
echo ""

echo "================================"
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "1. Edit .env and add your GROQ_API_KEY"
echo "2. Run: export \$(cat .env | xargs) && python3 main.py"
echo ""
echo "For deployment to Railway:"
echo "  See DEPLOYMENT.md for detailed instructions"
echo ""
echo "For GitHub:"
echo "  git add ."
echo "  git commit -m 'Initial commit'"
echo "  git remote add origin <your-repo-url>"
echo "  git push -u origin main"
echo ""
